### PR TITLE
EEGLAB plugin implementation

### PR DESCRIPTION
**Pull request by arnodelorme**
The additional code allows to import files in EEGLAB.

### CODE REVIEW

**Comment by MaxvandenBoom** [comment]
Great, thanks for the addition! I'll check it this week and merge.

Do you think it is possible to remove the binary from this pull request? There's a couple of other things I wil update/include this week and I'll update the binaries (mac and windows both) in one-go.

Also I'll set a github version/release for matmef after the coming week's update, guess it has matured enough to count as initial (1.0) From your commit, do I understand correctly that you want to keep your own version count for the EEGLab plugin within matmef?

**Comment by arnodelorme** [comment]
> Great, thanks for the addition! I'll check it this week and merge.
> 
> Do you think it is possible to remove the binary from this pull request?

Oh, yes, sorry about that.
But because they are small, they should be included. Most people will not know how to recompile these files.
I have left them for now.

> There's a couple of other things I wil update/include this week and I'll update the binaries (mac and windows both) in one-go.
> 
> Also I'll set a github version/release for matmef after the coming week's update, guess it has matured enough to count as initial (1.0) From your commit, do I understand correctly that you want to keep your own version count for the EEGLab plugin within matmef?

Perfect.

Cheers,

Arno

**Comment by MaxvandenBoom** [comment]
> But because they are small, they should be included. Most people will not know how to recompile these files. I have left them for now.

I understand and agree! I have already always included the binary files in this repo for both windows and mac. You can see, the mex functions `read_mef_ts_data` and `read_mef_session_metadata` are already there as `.mexmaci64 `and `.mexw64`. So feel free to remove your binary from the pull-request.

Best,
Max

**Comment by MaxvandenBoom** [comment]
Hi Arno,

I released the current repo state as v1.0.0 and will use github releases (from now on) as a means of versioning.

I prefer to not have the version changes in the README file. Instead, I will add them to the description in github upon each new release (including updates to the EEGLIB plugin). Meaning that once we have merged this EEGLab addition and are satisfied with it's workings, I will add the "initial release for EEGLAB plugin" line to the description of the next release.

Could you please remove the "version" adjustments you made to the readme file. Offcourse what you added to the acknowledgments should stay in and will be merged as it is :)

**Comment by arnodelorme** [comment]
Hi Max,

I tried removing the binary but it is not that simple. I would need to copy the old binary but even so, the Git history will choke and resubmit it to you these old files as new files (even though the binary are identical).
In any case, simply copy and resubmit the two files to your repo, ignoring the pull request.

https://github.com/arnodelorme/matmef/blob/master/eegplugin_matmef.m

https://github.com/arnodelorme/matmef/blob/master/pop_matmef.m

If you issue a new Github release, make sure the version number in (https://github.com/arnodelorme/matmef/blob/master/eegplugin_matmef.m) is the same as the GitHub release for consistency. If you could submit the plugin to 

https://sccn.ucsd.edu/eeglab/plugin_uploader/upload_form.php

That would be fantastic.

Cheers,

Arno

**Comment by MaxvandenBoom** [comment]
> Hi Max, I tried removing the binary but it is not that simple. I would need to copy the old binary but even so, the Git history will choke and resubmit it to you these old files as new files (even though the binary are identical). In any case, simply copy and resubmit the two files to your repo, ignoring the pull request. 

Aah, I would have liked to have you as a contributor in this repo that comes with the pull request :)
I can do it the way you propose. Alternatively you can add me as a [collaborator](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) to your fork and I will fix the conflicts for you.


> If you issue a new Github release, make sure the version number in (https://github.com/arnodelorme/matmef/blob/master/eegplugin_matmef.m) is the same as the GitHub release for consistency. 

I expected that, I will.

> If you could submit the plugin to https://sccn.ucsd.edu/eeglab/plugin_uploader/upload_form.php That would be fantastic.

Will do when it's done!

**Comment by arnodelorme** [comment]
> On Sep 28, 2021, at 9:42 AM, Max ***@***.***> wrote:
> 
> 
> Hi Max, I tried removing the binary but it is not that simple. I would need to copy the old binary but even so, the Git history will choke and resubmit it to you these old files as new files (even though the binary are identical). In any case, simply copy and resubmit the two files to your repo, ignoring the pull request.
> 
> Aah, I would have liked to have you as a contributor in this repo that comes with the pull request :)

Thanks. It is not important though so do not worry about it.

> I can do it the way you propose. Alternatively you can add me as a collaborator to your fork and I will fix the conflicts for you.

I have added you to the repo.

> If you issue a new Github release, make sure the version number in (https://github.com/arnodelorme/matmef/blob/master/eegplugin_matmef.m) is the same as the GitHub release for consistency.
> 
> I expected that, I will.
> 
> If you could submit the plugin to https://sccn.ucsd.edu/eeglab/plugin_uploader/upload_form.php That would be fantastic.
> 
> Will do when it's done!

Wonderful. Cheers,

Arno

**Comment by MaxvandenBoom** [comment]
Alright, resolved and merged! Thanks for your contribution :)

Before I submit it as a plugin, have you tested the EEGLab code already on a MEF3 dataset?
I'm asking since you were encountering some problems according to issue #2.

**Comment by arnodelorme** [comment]
It worked on Windows but not on Mac (I could not recompile on Mac and when I try using the stocked compiled file, I get a “beep” and Matlab hangs).

**Comment by MaxvandenBoom** [comment]
That's weird, I have never encountered the mac binary not working on any of the computer here in the lab :/

Could you try retrieving a fresh clone of Matmef and then using a low-level function to read the metadata like so:
`session = read_mef_session_metadata('/BIDS_MotorAmp/sub-01/ses-ieeg01/ieeg/sub-01_ses-ieeg01_task-finger_run-1234_ieeg.mefd', [], 1);`
Please make sure to also retrieve a fresh download of the dataset again from OSF (https://osf.io/vmxdn/), I updated it this morning to be complete.

I really appreciate your help in finding out what is happening here!

**Comment by arnodelorme** [comment]
Yes. That worked. Tx

**Comment by MaxvandenBoom** [comment]
@arnodelorme I submitted Matmef v1.1.0 as an EEGLab plugin just now, tnx!

**Comment by nedadel** [comment]
> Great, thanks for the addition! I'll check it this week and merge. Do you think it is possible to remove the binary from this pull request?
> Oh, yes, sorry about that. But because they are small, they should be included. Most people will not know how to recompile these files. I have left them for now.
> There's a couple of other things I wil update/include this week and I'll update the binaries (mac and windows both) in one-go. Also I'll set a github version/release for matmef after the coming week's update, guess it has matured enough to count as initial (1.0) From your commit, do I understand correctly that you want to keep your own version count for the EEGLab plugin within matmef?
> Perfect. Cheers, Arno
> […](#)
> — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.



> The additional code allows to import files in EEGLAB.

Hello,
Hope you are doing well and stay safe.
I’m dealing with this issue, AN ERROR in EEGLAB. I run ADJUST plugin to remove artifacts and this error occurred. ‘Error occurred in function ADJUST() at line 320’.
Would you please help me?
I’m using EEGLAB version 2021.0 and 2021.1
in MATLAB 2021.a

THX in advance for your assistance

**Comment by MaxvandenBoom** [comment]
Hi @nedadel 
I think you might have accidentally posted your issue in the wrong place, this repository is only about Matmef which - as far as I know - is unrelated to ADJUST.
If there is a problem with EEGLab, I suggest creating an issue there: https://github.com/sccn/eeglab
If there is a problem with the ADJUST plugin, I suggest contacting them.

**Pull request merged**
